base.url=https://www.saucedemo.com
browser=chrome
headless=false
implicit.wait=10
explicit.wait=15
page.load.timeout=30
valid.username=standard_user
valid.password=secret_sauce
locked.username=locked_out_user
report.path=test-output/ExtentReports/
report.name=Automation Test Report
#retry.count=2